# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install python-docx
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from docx import Document
from docx.shared import Inches

data={"EmployeeID":list(range(1,61)),
"Name":["Amit Sharma","Priya Verma","Ravi Kumar","Neha Singh","Rahul Mehta","Pooja Iyer","Suresh Reddy","Kiran Desai","Anjali Gupta","Vikram Joshi","Rohit Agarwal","Sneha Kapoor","Arjun Nair","Meera Pillai","Kunal Shah","Divya Bansal","Manish Tiwari","Nisha Arora","Aditya Mishra","Shreya Saxena","Vikas Yadav","Ritika Malhotra","Harsh Vardhan","Simran Kaur","Deepak Choudhary","Payal Jain","Aakash Pandey","Swati Goyal","Ankit Srivastava","Komal Bhatt","Varun Khanna","Tanvi Kulkarni","Nitin Patil","Rashmi Shetty","Abhishek Dubey","Pallavi Sinha","Gaurav Chauhan","Isha Mehta","Rajat Verma","Neeraj Singh","Sonal Gupta","Yash Agarwal","Pankaj Tripathi","Alok Ranjan","Madhuri Dixit","Rajeev Kumar","Bhavna Sharma","Sanjay Gupta","Preeti Arora","Mohit Bansal","Kavita Joshi","Ashish Yadav","Rekha Iyer","Dinesh Reddy","Shalini Nair","Tarun Desai","Geeta Kapoor","Prakash Mishra","Siddharth Malhotra"],
"Gender":["M","M","M","M","F","M","M","M","M","M","M","F","M","M","M","M","F","M","M","M","M","M","M","F","M","M","M","M","M","F","M","M","M","M","M","F","M","M","M","M","M","M","F","M","M","M","M","M","F","M","M","M","M","F","M","M","M","M","M","M"],
"Age":[28,26,35,30,40,32,45,29,27,38,31,24,33,29,36,28,41,27,34,26,37,30,32,28,39,25,31,27,33,29,36,28,40,35,30,27,38,26,34,42,29,31,45,37,33,39,28,41,30,35,27,32,36,44,29,38,31,40,34,37],
"Department":["IT","Finance","IT","HR","Marketing","IT","Finance","IT","HR","IT","Marketing","Finance","IT","HR","IT","Finance","Marketing","IT","HR","IT","IT","Finance","Marketing","IT","HR","Finance","IT","IT","Marketing","HR","IT","Finance","IT","HR","Marketing","IT","IT","Finance","HR","IT","Marketing","IT","Finance","IT","HR","IT","Marketing","Finance","IT","HR","IT","Finance","IT","HR","Marketing","IT","Finance","IT","HR","IT"],
"YearsExperience":[3,2,10,5,12,6,20,4,3,15,7,1,9,4,11,3,18,2,8,2,13,5,6,4,14,2,7,3,9,4,10,3,15,12,5,2,11,1,6,16,3,7,20,13,9,14,4,17,5,12,2,6,8,19,3,11,7,15,10,13],
"Salary":[50000,42000,95000,60000,105000,65000,120000,55000,58000,110000,70000,88000,92000,58000,102000,52000,115000,45000,85000,48000,98000,62000,67000,59000,102000,46000,72000,53000,88000,60000,95000,51000,110000,99000,61000,47000,97000,42000,69000,120000,56000,75000,130000,105000,82000,108000,59000,112000,64000,101000,48000,66000,87000,125000,55000,98000,72000,115000,90000,104000]}

min_len=min(len(v) for v in data.values())
for k in data:
    data[k]=data[k][:min_len]

df=pd.DataFrame(data)
df.to_csv("employee_data.csv",index=False)
summary=df.describe(include='all')
summary.to_csv("summary.csv")

doc=Document()
doc.add_heading("Employee Data Dashboard Report",0)

plt.figure()
sns.countplot(data=df,x='Gender')
plt.savefig("g1.png")
plt.close()
doc.add_heading("Gender Distribution",1)
doc.add_picture("g1.png",width=Inches(5))

plt.figure()
sns.countplot(data=df,x='Department')
plt.savefig("g2.png")
plt.close()
doc.add_heading("Department Distribution",1)
doc.add_picture("g2.png",width=Inches(5))

plt.figure()
sns.histplot(df['Age'])
plt.savefig("g3.png")
plt.close()
doc.add_heading("Age Distribution",1)
doc.add_picture("g3.png",width=Inches(5))

plt.figure()
sns.scatterplot(data=df,x='YearsExperience',y='Salary')
plt.savefig("g4.png")
plt.close()
doc.add_heading("Salary vs Experience",1)
doc.add_picture("g4.png",width=Inches(5))

doc.add_heading("Key Insights",1)
doc.add_paragraph("Most employees are male and IT department has highest count.")
doc.add_paragraph("Majority employees fall in mid age group.")
doc.add_paragraph("Salary increases with experience with some variation.")

doc.save("Employee_Report.docx")

from google.colab import files
files.download("Employee_Report.docx")